plugins {
    id "com.android.application"
}

if (file("google-services.json").exists()) {
    apply plugin: "com.google.gms.google-services"
}

android {
    namespace "com.ghas.lunch"
    compileSdk 36

    defaultConfig {
        applicationId "com.ghas.lunch"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform("com.google.firebase:firebase-bom:34.7.0")
    implementation "com.google.firebase:firebase-messaging"
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.activity:activity:1.12.1"
}
